languages:
   JavaScript: true
engines:
    fixme:
        enabled: true
    eslint:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - javascript
ratings:
   paths:
   - "app/**"
   - "addon/**"
exclude_paths:
- "config/**"
- "tests/*"
- "vendor/*"
- "ember-cli-build.js"
- "index.js"
- "testem.js"
